name: cnspec scan

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ trigger-scan ]

jobs:
  cnspec:
    name: scan
    runs-on: ubuntu-latest
    steps:
    - name: Debugging - Setting Git Tag
      run: |
        echo "Git tag received: ${{ github.event.client_payload.version }}"
        echo "GIT_TAG=${{ github.event.client_payload.version }}" >> $GITHUB_ENV

    - name: Debug - Print TAG
      run: |
        echo ${GIT_TAG}

    - uses: actions/checkout@v4

    - uses: mondoohq/actions@v11.0.0
      with:
        args: scan local --incognito --policy-bundle ./cnspec-policy.mql.yaml --score-threshold 100
