name: Package and publish

on:
  workflow_dispatch:


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - uses: actions/checkout@v4

    - name: Download release
      run: gh release download --repo ${PARENT_REPO} --pattern '*inux_*' --pattern 'checksums.txt'
      env:
        PARENT_REPO: ${{ secrets.PARENT_REPO }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Verify assets
      run: sha256sum -c ./checksums.txt --ignore-missing --strict

    - name: Extract
      run: |
        mkdir -p ./amd64 ./arm64
        tar -zxvf ./*_x86_64.tar.gz -C ./amd64
        tar -zxvf ./*_arm64.tar.gz -C ./arm64

    - name: Build and push (amd64)
      id: build
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64
        build-args: TARGET_ARCH=amd64
        push: true
        tags: ghcr.io/username-is-already-taken2/message-app:latest

    - name: Extract image details from build output
      run: |
        IMAGE_DIGEST=$(echo "${{ steps.build.outputs.digest }}")
        echo "Extracted Image Digest: $IMAGE_DIGEST"

        echo "${{ steps.build.outputs.metadata }}" > metadata.json
        # Extract the image name from metadata JSON using jq
        IMAGE_NAME=$(jq -r '.["image.name"]' metadata.json)

        # Output the extracted image name
        echo "Extracted Image Name: $IMAGE_NAME"
